# Generated by Django 2.1.5 on 2019-05-05 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assigncourse',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'AssignCourse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Assignmentsubmit',
            fields=[
                ('assignmentid', models.IntegerField(db_column='AssignmentId', primary_key=True, serialize=False)),
                ('assignment', models.CharField(db_column='Assignment', max_length=50)),
            ],
            options={
                'db_table': 'AssignmentSubmit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Assignmentupload',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('assignment', models.CharField(db_column='Assignment', max_length=50)),
            ],
            options={
                'db_table': 'AssignmentUpload',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Assignsalary',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('designation', models.CharField(db_column='Designation', max_length=50)),
                ('salary', models.CharField(db_column='Salary', max_length=50)),
            ],
            options={
                'db_table': 'AssignSalary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('status', models.BooleanField(db_column='Status')),
                ('date', models.DateField(db_column='Date')),
            ],
            options={
                'db_table': 'Attendance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Classcourses',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ClassCourses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=50)),
                ('fee', models.IntegerField(db_column='Fee')),
            ],
            options={
                'db_table': 'Classes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('coursecode', models.CharField(db_column='CourseCode', max_length=50)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Courses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Datesheet',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('date', models.DateTimeField(db_column='Date')),
            ],
            options={
                'db_table': 'DateSheet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('challanid', models.AutoField(db_column='ChallanId', primary_key=True, serialize=False)),
                ('month', models.CharField(db_column='Month', max_length=8)),
                ('duedate', models.DateField(db_column='DueDate')),
            ],
            options={
                'db_table': 'Fee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('username', models.CharField(db_column='UserName', max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(db_column='Password', max_length=50)),
                ('role', models.CharField(db_column='Role', max_length=50)),
            ],
            options={
                'db_table': 'Login',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='FirstName', max_length=50)),
                ('lastname', models.CharField(blank=True, db_column='LastName', max_length=50, null=True)),
                ('contact', models.CharField(blank=True, db_column='Contact', max_length=50, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=50, null=True)),
                ('dateofbirth', models.DateTimeField(db_column='DateOfBirth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], db_column='Gender', max_length=1)),
            ],
            options={
                'db_table': 'Person',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='Description', max_length=50)),
            ],
            options={
                'db_table': 'Request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('evaluationname', models.CharField(db_column='EvaluationName', max_length=50)),
                ('marks', models.IntegerField(db_column='Marks')),
            ],
            options={
                'db_table': 'Result',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Salary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=50)),
                ('strength', models.IntegerField(db_column='Strength')),
            ],
            options={
                'db_table': 'Section',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Studentsection',
            fields=[
                ('studentid', models.IntegerField(db_column='StudentId', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'StudentSection',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(db_column='DateTime')),
            ],
            options={
                'db_table': 'TimeTable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.ForeignKey(db_column='Id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='+', serialize=False, to='SMS.Person')),
                ('registrationno', models.CharField(db_column='RegistrationNo', max_length=50)),
            ],
            options={
                'db_table': 'Student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.ForeignKey(db_column='Id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='+', serialize=False, to='SMS.Person')),
                ('designation', models.CharField(db_column='Designation', max_length=50)),
            ],
            options={
                'db_table': 'Teacher',
                'managed': False,
            },
        ),
    ]
